[package]
name = "sake"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoin = { version = "0.32.5", features = ["rand-std"] }

[dev-dependencies]
proptest = "1.9.0"

bitcoin-script = { git = "https://github.com/BitVM/rust-bitcoin-script" }
